name: bindingforge
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - numpy>=1.21
  - pandas>=1.3
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  - rdkit>=2023.3
  - biopython>=1.81
  - openbabel
  - plip
  - pymol-open-source
  - jupyter
  - ipykernel
  - pip
  - pip:
    - autodock-vina
    - meeko
    - vina
